CREATE TABLE IF NOT EXISTS `graylist` (
`idx` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`url` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`cookie` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`date` DATETIME NOT NULL,
`status` VARCHAR( 8 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`reason` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
) ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_general_ci;
